/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
 * OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0>.
 */

/** @file opengl_shader.h OpenGL shader programs. */

/** Vertex shader that positions a sprite on screen.. */
static const char *_vertex_shader_sprite[] = {
	"#version 110\n",
	"uniform vec4 sprite;",
	"uniform vec2 screen;",
	"attribute vec2 position, colour_uv;",
	"varying vec2 colour_tex_uv;",
	"void main() {",
	"  vec2 size = sprite.zw / screen.xy;",
	"  vec2 offset = ((2.0 * sprite.xy + sprite.zw) / screen.xy - 1.0) * vec2(1.0, -1.0);",
	"  colour_tex_uv = colour_uv;",
	"  gl_Position = vec4(position * size + offset, 0.0, 1.0);",
	"}",
};

/** GLSL 1.50 vertex shader that positions a sprite on screen. */
static const char *_vertex_shader_sprite_150[] = {
	"#version 150\n",
	"uniform vec4 sprite;",
	"uniform vec2 screen;",
	"in vec2 position, colour_uv;",
	"out vec2 colour_tex_uv;",
	"void main() {",
	"  vec2 size = sprite.zw / screen.xy;",
	"  vec2 offset = ((2.0 * sprite.xy + sprite.zw) / screen.xy - 1.0) * vec2(1.0, -1.0);",
	"  colour_tex_uv = colour_uv;",
	"  gl_Position = vec4(position * size + offset, 0.0, 1.0);",
	"}",
};

/** Fragment shader that reads the fragment colour from a 32bpp texture. */
static const char *_frag_shader_direct[] = {
	"#version 110\n",
	"uniform sampler2D colour_tex;",
	"uniform float grade_saturation;",
	"uniform float grade_contrast;",
	"uniform float grade_gamma;",
	"uniform float tone_strength;",
	"uniform float bloom_strength;",
	"uniform vec2 texel_size;",
	"uniform float sharpen_strength;",
	"varying vec2 colour_tex_uv;",
	"vec3 sample_colour(vec2 uv) {",
	"  return texture2D(colour_tex, uv).rgb;",
	"}",
	"vec3 apply_grade(vec3 c) {",
	"  float luma = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  c = mix(vec3(luma), c, grade_saturation);",
	"  c = (c - 0.5) * grade_contrast + 0.5;",
	"  c = pow(max(c, vec3(0.0)), vec3(grade_gamma));",
	"  return clamp(c, 0.0, 1.0);",
	"}",
	"vec3 apply_tonemap(vec3 c) {",
	"  vec3 mapped = clamp((c * (2.51 * c + 0.03)) / (c * (2.43 * c + 0.59) + 0.14), 0.0, 1.0);",
	"  return mix(c, mapped, tone_strength);",
	"}",
	"vec3 apply_bloom(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 glow_src = (c + n + s + e + w) * 0.2;",
	"  float glow = smoothstep(0.72, 1.0, max(max(glow_src.r, glow_src.g), glow_src.b));",
	"  return clamp(c + glow_src * (bloom_strength * glow), 0.0, 1.0);",
	"}",
	"vec3 apply_sharpen(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 blur = (n + s + e + w + c) * 0.2;",
	"  float luma_c = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  float luma_delta = max(max(abs(luma_c - dot(n, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(s, vec3(0.2126, 0.7152, 0.0722)))),",
	"                       max(abs(luma_c - dot(e, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(w, vec3(0.2126, 0.7152, 0.0722)))));",
	"  float edge_gate = 1.0 - smoothstep(0.04, 0.22, luma_delta);",
	"  return clamp(c + (c - blur) * (sharpen_strength * edge_gate), 0.0, 1.0);",
	"}",
	"void main() {",
	"  vec4 col = texture2D(colour_tex, colour_tex_uv);",
	"  col.rgb = apply_grade(col.rgb);",
	"  col.rgb = apply_tonemap(col.rgb);",
	"  col.rgb = apply_bloom(colour_tex_uv, col.rgb);",
	"  col.rgb = apply_sharpen(colour_tex_uv, col.rgb);",
	"  gl_FragData[0] = col;",
	"}",
};

/** GLSL 1.50 fragment shader that reads the fragment colour from a 32bpp texture. */
static const char *_frag_shader_direct_150[] = {
	"#version 150\n",
	"uniform sampler2D colour_tex;",
	"uniform float grade_saturation;",
	"uniform float grade_contrast;",
	"uniform float grade_gamma;",
	"uniform float tone_strength;",
	"uniform float bloom_strength;",
	"uniform vec2 texel_size;",
	"uniform float sharpen_strength;",
	"in vec2 colour_tex_uv;",
	"out vec4 colour;",
	"vec3 sample_colour(vec2 uv) {",
	"  return texture(colour_tex, uv).rgb;",
	"}",
	"vec3 apply_grade(vec3 c) {",
	"  float luma = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  c = mix(vec3(luma), c, grade_saturation);",
	"  c = (c - 0.5) * grade_contrast + 0.5;",
	"  c = pow(max(c, vec3(0.0)), vec3(grade_gamma));",
	"  return clamp(c, 0.0, 1.0);",
	"}",
	"vec3 apply_tonemap(vec3 c) {",
	"  vec3 mapped = clamp((c * (2.51 * c + 0.03)) / (c * (2.43 * c + 0.59) + 0.14), 0.0, 1.0);",
	"  return mix(c, mapped, tone_strength);",
	"}",
	"vec3 apply_bloom(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 glow_src = (c + n + s + e + w) * 0.2;",
	"  float glow = smoothstep(0.72, 1.0, max(max(glow_src.r, glow_src.g), glow_src.b));",
	"  return clamp(c + glow_src * (bloom_strength * glow), 0.0, 1.0);",
	"}",
	"vec3 apply_sharpen(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 blur = (n + s + e + w + c) * 0.2;",
	"  float luma_c = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  float luma_delta = max(max(abs(luma_c - dot(n, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(s, vec3(0.2126, 0.7152, 0.0722)))),",
	"                       max(abs(luma_c - dot(e, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(w, vec3(0.2126, 0.7152, 0.0722)))));",
	"  float edge_gate = 1.0 - smoothstep(0.04, 0.22, luma_delta);",
	"  return clamp(c + (c - blur) * (sharpen_strength * edge_gate), 0.0, 1.0);",
	"}",
	"void main() {",
	"  colour = texture(colour_tex, colour_tex_uv);",
	"  colour.rgb = apply_grade(colour.rgb);",
	"  colour.rgb = apply_tonemap(colour.rgb);",
	"  colour.rgb = apply_bloom(colour_tex_uv, colour.rgb);",
	"  colour.rgb = apply_sharpen(colour_tex_uv, colour.rgb);",
	"}",
};

/** Fragment shader that performs a palette lookup to read the colour from an 8bpp texture. */
static const char *_frag_shader_palette[] = {
	"#version 110\n",
	"uniform sampler2D colour_tex;",
	"uniform sampler1D palette;",
	"uniform float grade_saturation;",
	"uniform float grade_contrast;",
	"uniform float grade_gamma;",
	"uniform float tone_strength;",
	"uniform float bloom_strength;",
	"uniform vec2 texel_size;",
	"uniform float sharpen_strength;",
	"varying vec2 colour_tex_uv;",
	"vec3 sample_colour(vec2 uv) {",
	"  float idx = texture2D(colour_tex, uv).r;",
	"  return texture1D(palette, idx).rgb;",
	"}",
	"vec3 apply_grade(vec3 c) {",
	"  float luma = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  c = mix(vec3(luma), c, grade_saturation);",
	"  c = (c - 0.5) * grade_contrast + 0.5;",
	"  c = pow(max(c, vec3(0.0)), vec3(grade_gamma));",
	"  return clamp(c, 0.0, 1.0);",
	"}",
	"vec3 apply_tonemap(vec3 c) {",
	"  vec3 mapped = clamp((c * (2.51 * c + 0.03)) / (c * (2.43 * c + 0.59) + 0.14), 0.0, 1.0);",
	"  return mix(c, mapped, tone_strength);",
	"}",
	"vec3 apply_bloom(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 glow_src = (c + n + s + e + w) * 0.2;",
	"  float glow = smoothstep(0.72, 1.0, max(max(glow_src.r, glow_src.g), glow_src.b));",
	"  return clamp(c + glow_src * (bloom_strength * glow), 0.0, 1.0);",
	"}",
	"vec3 apply_sharpen(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 blur = (n + s + e + w + c) * 0.2;",
	"  float luma_c = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  float luma_delta = max(max(abs(luma_c - dot(n, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(s, vec3(0.2126, 0.7152, 0.0722)))),",
	"                       max(abs(luma_c - dot(e, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(w, vec3(0.2126, 0.7152, 0.0722)))));",
	"  float edge_gate = 1.0 - smoothstep(0.04, 0.22, luma_delta);",
	"  return clamp(c + (c - blur) * (sharpen_strength * edge_gate), 0.0, 1.0);",
	"}",
	"void main() {",
	"  float idx = texture2D(colour_tex, colour_tex_uv).r;",
	"  vec4 col = texture1D(palette, idx);",
	"  col.rgb = apply_grade(col.rgb);",
	"  col.rgb = apply_tonemap(col.rgb);",
	"  col.rgb = apply_bloom(colour_tex_uv, col.rgb);",
	"  col.rgb = apply_sharpen(colour_tex_uv, col.rgb);",
	"  gl_FragData[0] = col;",
	"}",
};

/** GLSL 1.50 fragment shader that performs a palette lookup to read the colour from an 8bpp texture. */
static const char *_frag_shader_palette_150[] = {
	"#version 150\n",
	"uniform sampler2D colour_tex;",
	"uniform sampler1D palette;",
	"uniform float grade_saturation;",
	"uniform float grade_contrast;",
	"uniform float grade_gamma;",
	"uniform float tone_strength;",
	"uniform float bloom_strength;",
	"uniform vec2 texel_size;",
	"uniform float sharpen_strength;",
	"in vec2 colour_tex_uv;",
	"out vec4 colour;",
	"vec3 sample_colour(vec2 uv) {",
	"  float idx = texture(colour_tex, uv).r;",
	"  return texture(palette, idx).rgb;",
	"}",
	"vec3 apply_grade(vec3 c) {",
	"  float luma = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  c = mix(vec3(luma), c, grade_saturation);",
	"  c = (c - 0.5) * grade_contrast + 0.5;",
	"  c = pow(max(c, vec3(0.0)), vec3(grade_gamma));",
	"  return clamp(c, 0.0, 1.0);",
	"}",
	"vec3 apply_tonemap(vec3 c) {",
	"  vec3 mapped = clamp((c * (2.51 * c + 0.03)) / (c * (2.43 * c + 0.59) + 0.14), 0.0, 1.0);",
	"  return mix(c, mapped, tone_strength);",
	"}",
	"vec3 apply_bloom(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 glow_src = (c + n + s + e + w) * 0.2;",
	"  float glow = smoothstep(0.72, 1.0, max(max(glow_src.r, glow_src.g), glow_src.b));",
	"  return clamp(c + glow_src * (bloom_strength * glow), 0.0, 1.0);",
	"}",
	"vec3 apply_sharpen(vec2 uv, vec3 c) {",
	"  vec3 n = sample_colour(uv + vec2(0.0, -texel_size.y));",
	"  vec3 s = sample_colour(uv + vec2(0.0,  texel_size.y));",
	"  vec3 e = sample_colour(uv + vec2( texel_size.x, 0.0));",
	"  vec3 w = sample_colour(uv + vec2(-texel_size.x, 0.0));",
	"  vec3 blur = (n + s + e + w + c) * 0.2;",
	"  float luma_c = dot(c, vec3(0.2126, 0.7152, 0.0722));",
	"  float luma_delta = max(max(abs(luma_c - dot(n, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(s, vec3(0.2126, 0.7152, 0.0722)))),",
	"                       max(abs(luma_c - dot(e, vec3(0.2126, 0.7152, 0.0722))), abs(luma_c - dot(w, vec3(0.2126, 0.7152, 0.0722)))));",
	"  float edge_gate = 1.0 - smoothstep(0.04, 0.22, luma_delta);",
	"  return clamp(c + (c - blur) * (sharpen_strength * edge_gate), 0.0, 1.0);",
	"}",
	"void main() {",
	"  float idx = texture(colour_tex, colour_tex_uv).r;",
	"  colour = texture(palette, idx);",
	"  colour.rgb = apply_grade(colour.rgb);",
	"  colour.rgb = apply_tonemap(colour.rgb);",
	"  colour.rgb = apply_bloom(colour_tex_uv, colour.rgb);",
	"  colour.rgb = apply_sharpen(colour_tex_uv, colour.rgb);",
	"}",
};


/** Fragment shader function for remap brightness modulation. */
static const char *_frag_shader_remap_func = \
	"float max3(vec3 v) {"
	"  return max(max(v.x, v.y), v.z);"
	"}"
	""
	"vec3 adj_brightness(vec3 colour, float brightness) {"
	"  vec3 adj = colour * (brightness > 0.0 ? brightness / 0.5 : 1.0);"
	"  vec3 ob_vec = clamp(adj - 1.0, 0.0, 1.0);"
	"  float ob = (ob_vec.r + ob_vec.g + ob_vec.b) / 2.0;"
	""
	"  return clamp(adj + ob * (1.0 - adj), 0.0, 1.0);"
	"}";

/** Fragment shader that performs a palette lookup to read the colour from an 8bpp texture. */
static const char *_frag_shader_rgb_mask_blend[] = {
	"#version 110\n",
	"#extension GL_ATI_shader_texture_lod: enable\n",
	"#extension GL_ARB_shader_texture_lod: enable\n",
	"uniform sampler2D colour_tex;",
	"uniform sampler1D palette;",
	"uniform sampler2D remap_tex;",
	"uniform bool rgb;",
	"uniform float zoom;",
	"varying vec2 colour_tex_uv;",
	"",
	_frag_shader_remap_func,
	"",
	"void main() {",
	"  float idx = texture2DLod(remap_tex, colour_tex_uv, zoom).r;",
	"  vec4 remap_col = texture1D(palette, idx);",
	"  vec4 rgb_col = texture2DLod(colour_tex, colour_tex_uv, zoom);",
	"",
	"  gl_FragData[0].a = rgb ? rgb_col.a : remap_col.a;",
	"  gl_FragData[0].rgb = idx > 0.0 ? adj_brightness(remap_col.rgb, max3(rgb_col.rgb)) : rgb_col.rgb;",
	"}",
};

/** GLSL 1.50 fragment shader that performs a palette lookup to read the colour from an 8bpp texture. */
static const char *_frag_shader_rgb_mask_blend_150[] = {
	"#version 150\n",
	"uniform sampler2D colour_tex;",
	"uniform sampler1D palette;",
	"uniform sampler2D remap_tex;",
	"uniform float zoom;",
	"uniform bool rgb;",
	"in vec2 colour_tex_uv;",
	"out vec4 colour;",
	"",
	_frag_shader_remap_func,
	"",
	"void main() {",
	"  float idx = textureLod(remap_tex, colour_tex_uv, zoom).r;",
	"  vec4 remap_col = texture(palette, idx);",
	"  vec4 rgb_col = textureLod(colour_tex, colour_tex_uv, zoom);",
	"",
	"  colour.a = rgb ? rgb_col.a : remap_col.a;",
	"  colour.rgb = idx > 0.0 ? adj_brightness(remap_col.rgb, max3(rgb_col.rgb)) : rgb_col.rgb;",
	"}",
};

/** Fragment shader that performs a palette lookup to read the colour from a sprite texture. */
static const char *_frag_shader_sprite_blend[] = {
	"#version 110\n",
	"#extension GL_ATI_shader_texture_lod: enable\n",
	"#extension GL_ARB_shader_texture_lod: enable\n",
	"uniform sampler2D colour_tex;",
	"uniform sampler1D palette;",
	"uniform sampler2D remap_tex;",
	"uniform sampler1D pal;",
	"uniform float zoom;",
	"uniform bool rgb;",
	"uniform bool crash;",
	"varying vec2 colour_tex_uv;",
	"",
	_frag_shader_remap_func,
	"",
	"void main() {",
	"  float idx = texture2DLod(remap_tex, colour_tex_uv, zoom).r;",
	"  float r = texture1D(pal, idx).r;",
	"  vec4 remap_col = texture1D(palette, idx);",
	"  vec4 rgb_col = texture2DLod(colour_tex, colour_tex_uv, zoom);",
	"",
	"  if (crash && idx == 0.0) rgb_col.rgb = vec2(dot(rgb_col.rgb, vec3(0.199325561523, 0.391342163085, 0.076004028320)), 0.0).rrr;"
	"  gl_FragData[0].a = rgb && (r > 0.0 || idx == 0.0) ? rgb_col.a : remap_col.a;",
	"  gl_FragData[0].rgb = idx > 0.0 ? adj_brightness(remap_col.rgb, max3(rgb_col.rgb)) : rgb_col.rgb;",
	"}",
};

/** GLSL 1.50 fragment shader that performs a palette lookup to read the colour from a sprite texture. */
static const char *_frag_shader_sprite_blend_150[] = {
	"#version 150\n",
	"uniform sampler2D colour_tex;",
	"uniform sampler1D palette;",
	"uniform sampler2D remap_tex;",
	"uniform sampler1D pal;",
	"uniform float zoom;",
	"uniform bool rgb;",
	"uniform bool crash;",
	"in vec2 colour_tex_uv;",
	"out vec4 colour;",
	"",
	_frag_shader_remap_func,
	"",
	"void main() {",
	"  float idx =  textureLod(remap_tex, colour_tex_uv, zoom).r;"
	"  float r = texture(pal, idx).r;",
	"  vec4 remap_col = texture(palette, r);",
	"  vec4 rgb_col = textureLod(colour_tex, colour_tex_uv, zoom);",
	"",
	"  if (crash && idx == 0.0) rgb_col.rgb = vec2(dot(rgb_col.rgb, vec3(0.199325561523, 0.391342163085, 0.076004028320)), 0.0).rrr;"
	"  colour.a = rgb && (r > 0.0 || idx == 0.0) ? rgb_col.a : remap_col.a;",
	"  colour.rgb = idx > 0.0 ? adj_brightness(remap_col.rgb, max3(rgb_col.rgb)) : rgb_col.rgb;",
	"}",
};
